apiVersion: v1

kind: Service

metadata:

  name: pipeline-springboot

  namespace: payments-dev    # Kubernets namespace

  labels:

    app: pipeline-springboot

    service: springboot-service

    env: nonprod

spec:

  selector:

    app: pipeline-springboot

    service: springboot

    env: nonprod

  ports:

    - name: http

      port: 8080

      targetPort: 8080

      protocol: TCP
